-- ============================================================================
-- KoriAI SQL practice script
--
-- A trimmed-down copy of this project's real schema + seed data, so you can
-- run the same kinds of queries used in the mapper files against a throwaway
-- database, without touching the real app or its Flyway history.
--
-- HOW TO RUN
--   1. Create a scratch database (don't reuse the app's real "aitestdb"):
--        psql -U postgres -c "CREATE DATABASE sql_practice;"
--   2. Connect to it and run this whole file:
--        psql -U postgres -d sql_practice -f sql-practice/practice.sql
--      (or open it in DBeaver / IntelliJ's Database tool and run the script)
--   3. Scroll to "PART 3: EXERCISES" and try each TODO yourself before
--      looking at the ANSWER KEY at the bottom of the file.
--
-- This script is throwaway — DROP the database when you're done practicing.
-- ============================================================================


-- ============================================================================
-- PART 1: SCHEMA (trimmed from db/migration/V1, V19, V24, V28)
-- ============================================================================

DROP TABLE IF EXISTS tasks, goal_stars, goals, sentence_corrections, users CASCADE;

CREATE EXTENSION IF NOT EXISTS pgcrypto; -- gives us gen_random_uuid()

CREATE TABLE users (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                   VARCHAR(255) NOT NULL UNIQUE,
    display_name            VARCHAR(100) NOT NULL,
    korean_level            VARCHAR(20)  NOT NULL DEFAULT 'BEGINNER',
    timezone                TEXT         NOT NULL DEFAULT 'UTC',
    reminder_offset_minutes INTEGER      NOT NULL DEFAULT 30,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE sentence_corrections (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    original_text  TEXT NOT NULL,
    corrected_text TEXT NOT NULL,
    grammar_points JSONB,            -- e.g. ["past tense", "honorifics"]
    repetitions    INTEGER NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE goals (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title       TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'active',
    is_public   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE goal_stars (
    user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    goal_id    UUID   NOT NULL REFERENCES goals (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, goal_id)
);

CREATE TABLE tasks (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    goal_id          UUID REFERENCES goals (id) ON DELETE CASCADE,
    user_id          BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title            TEXT NOT NULL,
    completed        BOOLEAN NOT NULL DEFAULT FALSE,
    start_date       TIMESTAMPTZ,
    end_date         TIMESTAMPTZ,
    daily_start_time TIME,
    daily_end_time   TIME,
    tags             TEXT[] NOT NULL DEFAULT '{}',
    reminder_sent_at TIMESTAMPTZ,
    due_soon_sent_at TIMESTAMPTZ,
    overdue_sent_at  TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================================
-- PART 2: SEED DATA
-- ============================================================================

INSERT INTO users (email, display_name, korean_level, timezone, reminder_offset_minutes) VALUES
    ('heang@example.com', 'Heang',  'INTERMEDIATE', 'Asia/Seoul',    30),
    ('jane@example.com',  'Jane',   'BEGINNER',     'America/New_York', 15);

INSERT INTO sentence_corrections (user_id, original_text, corrected_text, grammar_points, repetitions) VALUES
    (1, '저는 학교에 갔어요', '저는 학교에 갔습니다', '["formal speech level"]'::jsonb, 0),
    (1, '나는 밥을 먹다',     '저는 밥을 먹어요',     '["politeness", "verb conjugation"]'::jsonb, 2),
    (2, '안녕 친구',          '안녕하세요',           '["greetings"]'::jsonb, 1);

INSERT INTO goals (id, user_id, title, status, is_public) VALUES
    ('11111111-1111-1111-1111-111111111111', 1, 'Pass TOPIK II', 'active', true),
    ('22222222-2222-2222-2222-222222222222', 1, 'Read 10 short stories', 'active', false),
    ('33333333-3333-3333-3333-333333333333', 2, 'Learn 500 words', 'active', true);

INSERT INTO goal_stars (user_id, goal_id) VALUES
    (1, '33333333-3333-3333-3333-333333333333'); -- Heang starred Jane's public goal

-- Tasks: mix of completed/incomplete, with/without daily times, with/without tags.
INSERT INTO tasks (goal_id, user_id, title, completed, start_date, end_date, daily_start_time, daily_end_time, tags) VALUES
    ('11111111-1111-1111-1111-111111111111', 1, 'Study grammar ch.3', false, NOW() - INTERVAL '1 day', NOW() + INTERVAL '6 days', '09:00', '10:00', ARRAY['grammar','topik']),
    ('11111111-1111-1111-1111-111111111111', 1, 'Practice listening',  false, NOW(),               NOW() + INTERVAL '1 day', '20:00', '21:00', ARRAY['listening']),
    (NULL,                                    1, 'Daily vocab review',  false, NOW(),               NULL,                       '08:00', NULL,      ARRAY['vocab','daily']),
    ('22222222-2222-2222-2222-222222222222', 1, 'Finish short story 1', true,  NOW() - INTERVAL '3 days', NOW() - INTERVAL '1 day', NULL, NULL, ARRAY[]::text[]),
    ('33333333-3333-3333-3333-333333333333', 2, 'Flashcards 1-50',     false, NOW(),               NOW() + INTERVAL '2 days', '07:00', '07:30', ARRAY['vocab']);


-- ============================================================================
-- PART 3: WORKED EXAMPLES (mirrors mapper SQL you've already seen in the repo)
-- ============================================================================

-- 3.1 Plain CRUD — like AchievementMapper / TelegramLinkMapper -------------
SELECT id, email, display_name, korean_level FROM users ORDER BY id;

-- 3.2 Upsert ("INSERT ... ON CONFLICT") — like FoundationProgressMapper.upsert
INSERT INTO goal_stars (user_id, goal_id) VALUES (1, '11111111-1111-1111-1111-111111111111')
ON CONFLICT (user_id, goal_id) DO NOTHING;          -- run this twice; 2nd run inserts 0 rows

-- 3.3 JSONB read/write — like SentenceCorrectionMapper -----------------------
SELECT id, original_text, grammar_points, grammar_points::text AS grammar_points_as_text
FROM sentence_corrections
WHERE user_id = 1;

-- pull one element out of the JSON array:
SELECT id, grammar_points -> 0 AS first_point        -- -> keeps JSON type
FROM sentence_corrections
WHERE jsonb_array_length(grammar_points) > 0;

-- 3.4 Array column — like tasks.tags (TaskMapper) ---------------------------
SELECT id, title, tags FROM tasks WHERE 'vocab' = ANY(tags);   -- array membership test
SELECT id, title, tags FROM tasks WHERE tags && ARRAY['grammar','listening']; -- "overlaps"

-- 3.5 EXISTS subquery — like GoalStarMapper.existsStar -----------------------
SELECT CASE WHEN EXISTS (
    SELECT 1 FROM goal_stars WHERE user_id = 1 AND goal_id = '33333333-3333-3333-3333-333333333333'
) THEN 1 ELSE 0 END AS starred;

-- 3.6 Correlated subquery enrichment — like GoalMapper.findAccessibleByUser
SELECT
    g.id, g.title,
    (SELECT COUNT(*) FROM tasks t WHERE t.goal_id = g.id)               AS task_total,
    (SELECT COUNT(*) FROM tasks t WHERE t.goal_id = g.id AND t.completed) AS task_completed,
    EXISTS (SELECT 1 FROM goal_stars s WHERE s.goal_id = g.id AND s.user_id = 1) AS starred
FROM goals g
WHERE g.user_id = 1
ORDER BY g.created_at DESC;

-- 3.7 CTE + timezone math — like TaskMapper.findDueReminders ----------------
WITH computed AS (
    SELECT
        t.id AS task_id,
        t.title,
        u.reminder_offset_minutes AS offset_min,
        (
            (date(t.start_date AT TIME ZONE COALESCE(u.timezone, 'UTC')) + t.daily_start_time)
                AT TIME ZONE COALESCE(u.timezone, 'UTC')
        ) AS start_instant
    FROM tasks t
    JOIN users u ON u.id = t.user_id
    WHERE t.completed = false
      AND t.daily_start_time IS NOT NULL
      AND t.reminder_sent_at IS NULL
)
SELECT task_id, title, start_instant, offset_min
FROM computed
WHERE start_instant > now()
  AND (start_instant - make_interval(mins => offset_min)) <= now();
-- Try changing a task's start_date/daily_start_time in PART 2 and re-running
-- this to see rows enter/leave the result.


-- ============================================================================
-- PART 4: EXERCISES — write these yourself, then check PART 5 (ANSWER KEY)
-- ============================================================================

-- Exercise 1: List every task title and its tags for user_id = 1, ordered so
-- the soonest start_date comes first (NULLs last).
-- TODO: write your SELECT here


-- Exercise 2: Count how many incomplete tasks each user has. One row per
-- user, columns: user_id, display_name, incomplete_count. (GROUP BY)
-- TODO: write your SELECT here


-- Exercise 3: Find every goal that is_public = true AND has at least one
-- task. Use EXISTS, not a JOIN.
-- TODO: write your SELECT here


-- Exercise 4: Add a grammar_points entry to one of Jane's corrections using
-- jsonb concatenation (the `||` operator), without overwriting what's there.
-- Hint: UPDATE ... SET grammar_points = grammar_points || '[...]'::jsonb
-- TODO: write your UPDATE here


-- Exercise 5 (hard): Write the "due-soon" query — same shape as 3.7, but
-- based on daily_end_time/end_date instead of daily_start_time/start_date,
-- and using due_soon_sent_at instead of reminder_sent_at as the dedupe guard.
-- (This is exactly DailyEndTime version in TaskMapper.findDueSoonReminders.)
-- TODO: write your WITH...SELECT here


-- ============================================================================
-- PART 5: ANSWER KEY (no peeking until you've tried Part 4!)
-- ============================================================================

-- -- Exercise 1
-- SELECT title, tags
-- FROM tasks
-- WHERE user_id = 1
-- ORDER BY start_date NULLS LAST;

-- -- Exercise 2
-- SELECT u.id AS user_id, u.display_name, COUNT(t.id) AS incomplete_count
-- FROM users u
-- LEFT: JOIN tasks t ON t.user_id = u.id AND t.completed = false
-- GROUP BY u.id, u.display_name
-- ORDER BY u.id;

-- -- Exercise 3
-- SELECT g.id, g.title
-- FROM goals g
-- WHERE g.is_public = true
--   AND EXISTS (SELECT 1 FROM tasks t WHERE t.goal_id = g.id);

-- -- Exercise 4
-- UPDATE sentence_corrections
-- SET grammar_points = COALESCE(grammar_points, '[]'::jsonb) || '["sentence ending"]'::jsonb
-- WHERE user_id = 2 AND id = 3;

-- -- Exercise 5
-- WITH computed AS (
--     SELECT
--         t.id AS task_id,
--         t.title,
--         u.reminder_offset_minutes AS offset_min,
--         (
--             (date(t.end_date AT TIME ZONE COALESCE(u.timezone, 'UTC')) + t.daily_end_time)
--                 AT TIME ZONE COALESCE(u.timezone, 'UTC')
--         ) AS end_instant
--     FROM tasks t
--     JOIN users u ON u.id = t.user_id
--     WHERE t.completed = false
--       AND t.daily_end_time IS NOT NULL
--       AND t.due_soon_sent_at IS NULL
-- )
-- SELECT task_id, title, end_instant
-- FROM computed
-- WHERE end_instant > now()
--   AND (end_instant - make_interval(mins => offset_min)) <= now();
