CREATE TABLE IF NOT EXISTS listening_lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    topic VARCHAR(80) NOT NULL,
    title VARCHAR(200) NOT NULL,
    level VARCHAR(30) NOT NULL DEFAULT 'BEGINNER',
    transcript JSONB NOT NULL DEFAULT '[]',
    quiz JSONB NOT NULL DEFAULT '[]',
    model_used VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_listening_lessons_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_listening_lessons_user ON listening_lessons (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS listening_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    lesson_id BIGINT NOT NULL,
    score INTEGER NOT NULL DEFAULT 0,
    total INTEGER NOT NULL DEFAULT 0,
    accuracy INTEGER NOT NULL DEFAULT 0,
    completed BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_listening_attempts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_listening_attempts_lesson FOREIGN KEY (lesson_id) REFERENCES listening_lessons (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_listening_attempts_user ON listening_attempts (user_id, created_at DESC);
