CREATE TABLE IF NOT EXISTS achievements (
    code VARCHAR(50) PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(300) NOT NULL,
    icon VARCHAR(50) NOT NULL DEFAULT 'trophy',
    category VARCHAR(50) NOT NULL,
    xp INTEGER NOT NULL DEFAULT 0,
    metric VARCHAR(50) NOT NULL,
    threshold INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS user_achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    achievement_code VARCHAR(50) NOT NULL,
    unlocked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_user_achievements_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_achievements_code FOREIGN KEY (achievement_code) REFERENCES achievements (code) ON DELETE CASCADE,
    CONSTRAINT uq_user_achievement UNIQUE (user_id, achievement_code)
);

CREATE INDEX IF NOT EXISTS idx_user_achievements_user ON user_achievements (user_id);

-- Seed achievement catalog. metric drives the unlock check in AchievementService.
INSERT INTO achievements (code, title, description, icon, category, xp, metric, threshold, sort_order) VALUES
    ('FIRST_STEPS',     'Beginner Survivor',            'Complete your first learning activity.',                'sprout',     'Milestone', 50,  'activity',  1,  1),
    ('WORD_COLLECTOR',  'Word Collector',               'Save 10 vocabulary words.',                             'book',       'Vocabulary',100, 'vocab',     10, 2),
    ('VOCAB_MASTER',    'Vocabulary Expert',            'Save 50 vocabulary words.',                             'library',    'Vocabulary',250, 'vocab',     50, 3),
    ('STREAK_7',        '7-Day Streak',                 'Practice 7 days in a row.',                             'flame',      'Consistency',150,'streak',    7,  4),
    ('STREAK_30',       '30-Day Streak',                'Practice 30 days in a row.',                            'flame',      'Consistency',500,'streak',    30, 5),
    ('GRAMMAR_POLISHER','Grammar Polisher',             'Run 10 sentence corrections.',                          'spell-check','Writing',   150, 'corrections',10, 6),
    ('DILIGENT_WRITER', 'Diligent Writer',              'Write 5 diary entries.',                                'notebook',   'Writing',   150, 'diary',     5,  7),
    ('GOOD_LISTENER',   'Good Listener',                'Complete 5 listening lessons.',                         'headphones', 'Listening', 200, 'listening', 5,  8),
    ('CONVERSATIONALIST','Workplace Communicator',      'Send 20 messages to the AI coach.',                     'messages',   'Speaking',  200, 'chat',      20, 9);
