-- Module 9: Real Workplace Korean Analyzer
CREATE TABLE IF NOT EXISTS message_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    source VARCHAR(50) NULL,
    original_text TEXT NOT NULL,
    literal_meaning TEXT NULL,
    natural_meaning TEXT NULL,
    business_context TEXT NULL,
    politeness_level VARCHAR(255) NULL,
    tone VARCHAR(255) NULL,
    breakdown JSONB NOT NULL DEFAULT '[]'::jsonb,
    suggested_replies JSONB NOT NULL DEFAULT '[]'::jsonb,
    model_used VARCHAR(100) NOT NULL DEFAULT 'gpt-5-mini',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_message_analysis_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_message_analysis_user_created
    ON message_analysis (user_id, created_at DESC);

-- Allow the new ANALYZER feature in api usage logging.
ALTER TABLE api_usage_logs DROP CONSTRAINT IF EXISTS ck_api_usage_logs_feature;

ALTER TABLE api_usage_logs ADD CONSTRAINT ck_api_usage_logs_feature
    CHECK (feature IN (
        'CHAT',
        'CORRECTION',
        'DIARY_FEEDBACK',
        'VOCAB_EXPLANATION',
        'VOCAB_GENERATION',
        'GRAMMAR_EXPLANATION',
        'DAILY_PHRASE',
        'MESSAGE_GEN',
        'LISTENING',
        'ANALYZER'
    ));
