CREATE TABLE IF NOT EXISTS reading_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    episode VARCHAR(60),
    title VARCHAR(200) NOT NULL,
    title_english VARCHAR(200) NOT NULL,
    category VARCHAR(40) NOT NULL DEFAULT 'DAILY_LIFE',
    level VARCHAR(30) NOT NULL DEFAULT 'Beginner',
    summary TEXT,
    source VARCHAR(200),
    grammar_note JSONB,
    paragraphs JSONB NOT NULL DEFAULT '[]',
    vocab JSONB NOT NULL DEFAULT '[]',
    quiz JSONB NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_reading_units_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_reading_units_user ON reading_units (user_id, created_at DESC);
