-- Stores the written interview script a candidate prepares per exam topic.
-- One row per (user, topic); sections is a JSON object keyed by outline section id.
CREATE TABLE IF NOT EXISTS interview_scripts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    topic_id VARCHAR(60) NOT NULL,
    sections JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_interview_scripts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_interview_scripts_user_topic UNIQUE (user_id, topic_id)
);

CREATE INDEX IF NOT EXISTS idx_interview_scripts_user ON interview_scripts (user_id);
