-- Core schema for KoriAI (PostgreSQL)
-- Tables:
-- 1) users
-- 2) conversations
-- 3) messages
-- 4) api_usage_logs
-- 5) sentence_corrections
-- 6) diary_entries

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    korean_level VARCHAR(20) NOT NULL DEFAULT 'BEGINNER',
    preferred_model VARCHAR(100) NOT NULL DEFAULT 'gpt-5-mini',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_users_email_lowercase CHECK (email = LOWER(email)),
    CONSTRAINT ck_users_korean_level CHECK (korean_level IN ('BEGINNER', 'ELEMENTARY', 'INTERMEDIATE', 'UPPER_INTERMEDIATE', 'ADVANCED', 'NATIVE'))
);

CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    scenario_id BIGINT NULL,
    title VARCHAR(200) NOT NULL,
    conversation_type VARCHAR(50) NOT NULL,
    model_used VARCHAR(100) NOT NULL DEFAULT 'gpt-5-mini',
    message_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_conversations_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_conversations_type CHECK (conversation_type IN ('FREE_CHAT', 'ROLE_PLAY', 'GRAMMAR_PRACTICE', 'VOCAB_PRACTICE', 'PRONUNCIATION', 'DIARY_COACH'))
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    corrections JSONB NULL,
    tokens_used INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE,
    CONSTRAINT ck_messages_role CHECK (role IN ('SYSTEM', 'USER', 'ASSISTANT', 'TOOL'))
);

CREATE TABLE IF NOT EXISTS api_usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    model VARCHAR(100) NOT NULL,
    feature VARCHAR(50) NOT NULL,
    prompt_tokens INTEGER NOT NULL DEFAULT 0,
    completion_tokens INTEGER NOT NULL DEFAULT 0,
    estimated_cost_usd NUMERIC(12, 6) NOT NULL DEFAULT 0.000000,
    response_time_ms INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_api_usage_logs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_api_usage_logs_feature CHECK (feature IN ('CHAT', 'CORRECTION', 'DIARY_FEEDBACK', 'VOCAB_EXPLANATION', 'GRAMMAR_EXPLANATION'))
);

CREATE TABLE IF NOT EXISTS sentence_corrections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    original_text TEXT NOT NULL,
    corrected_text TEXT NOT NULL,
    explanation TEXT NOT NULL,
    grammar_points JSONB NULL,
    model_used VARCHAR(100) NOT NULL DEFAULT 'gpt-5-mini',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_sentence_corrections_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS diary_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    entry_date DATE NOT NULL,
    original_text TEXT NOT NULL,
    corrected_text TEXT NOT NULL,
    feedback TEXT NOT NULL,
    word_count INTEGER NOT NULL DEFAULT 0,
    mood VARCHAR(30) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_diary_entries_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_conversations_user_id ON conversations (user_id);
CREATE INDEX IF NOT EXISTS idx_conversations_created_at ON conversations (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages (conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_api_usage_logs_user_id ON api_usage_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_api_usage_logs_feature ON api_usage_logs (feature);
CREATE INDEX IF NOT EXISTS idx_api_usage_logs_created_at ON api_usage_logs (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sentence_corrections_user_id ON sentence_corrections (user_id);
CREATE INDEX IF NOT EXISTS idx_sentence_corrections_created_at ON sentence_corrections (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_diary_entries_user_id ON diary_entries (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_diary_entries_user_date ON diary_entries (user_id, entry_date);

