-- Seed two more beginner Korean podcast reading units (Choisusu EP 02 & EP 03)
-- for the owner account (user_id = 1). Guarded on the user existing so the
-- migration is a no-op on fresh/local databases where user 1 does not exist.
-- Uses dollar-quoted (`$json$...$json$::jsonb`) literals so Korean text and
-- apostrophes need no escaping.

INSERT INTO reading_units (user_id, episode, title, title_english, category, level, summary, source,
                           grammar_note, paragraphs, vocab, quiz)
SELECT 1, 'EP 02', '날씨와 계절', 'Weather and Seasons', 'DAILY_LIFE', 'Beginner',
       'A beginner tour of Korea''s four seasons and the weather, activities, and foods that go with each: spring flowers and strawberries, hot rainy summers with bingsu and watermelon, cool autumn foliage and clothes, and snowy winters with skiing.',
       'Choisusu Korean Podcast',
       $json${
         "pattern": "A/V + -지만 (but)",
         "explanation": "Attach -지만 to a verb or adjective stem to contrast two clauses (\"but / although\"). Example: 봄에는 낮에는 따뜻하지만 밤에는 추워요 = In spring it is warm during the day but cold at night. The episode also teaches 제일/가장 = \"the most\": 딸기 빙수를 제일 좋아해요."
       }$json$::jsonb,
       $json$[
         {"korean": "여러분 안녕하세요~ 오늘은 날씨와 계절, 그 계절에 많이 먹는 음식에 대해서 이야기할 거예요. 요즘 여러분의 나라에 날씨는 어때요? 지금 무슨 계절이에요? 지금 한국은 5월이고 계절은 봄이에요. 한국의 계절은 봄, 여름, 가을, 겨울이 있어요. 보통 3월부터 5월까지 봄이고, 6월부터 8월까지 여름, 9월부터 11월까지 가을, 12월부터 2월까지 겨울이에요.", "english": "Hello everyone~ Today I am going to talk about weather and the seasons, and the foods people eat a lot in each season. How is the weather in your country these days? What season is it now? Right now it is May in Korea and the season is spring. Korea has four seasons: spring, summer, autumn, and winter. Usually spring is from March to May, summer from June to August, autumn from September to November, and winter from December to February."},
         {"korean": "한국의 봄에는 꽃이 많이 피는데 3월에는 추워서 꽃이 조금 피어요. 4월에 날씨가 3월보다 따뜻하고 날씨도 더 좋아서 4월에 꽃이 많이 피어요. 꽃이 많이 피면 사람들이 꽃구경을 하러 가요. 보통 친구 또는 남자친구, 여자친구하고 같이 꽃구경을 해요. 꽃 사진도 많이 찍고 서로 사진을 찍어 줘요.", "english": "In spring in Korea many flowers bloom, but in March it is cold so only a few bloom. In April the weather is warmer than in March and nicer, so many flowers bloom in April. When lots of flowers bloom, people go out to see them. Usually I go flower-viewing with a friend, boyfriend, or girlfriend. We take lots of flower photos and take pictures of each other."},
         {"korean": "그리고 봄에는 벚꽃 축제가 있어서 놀러 갈 수 있어요. 공원에도 꽃이 많이 피어서 공원에서도 꽃 구경을 할 수 있어요. 봄에는 낮에는 따뜻하지만 밤에는 추워요. 하지만 보통 날씨가 좋아서 많은 사람들이 밖에 나가서 놀아요.", "english": "Also, in spring there are cherry blossom festivals, so you can go out and have fun. Many flowers bloom in the parks too, so you can enjoy the flowers there as well. In spring it is warm during the day but cold at night. Still, the weather is usually nice, so many people go outside and have fun."},
         {"korean": "봄에 많이 먹는 과일은 딸기예요. 그래서 카페에서 딸기 라테, 딸기 스무디, 딸기 티라미수 등 딸기로 만든 것들이 많아요. 여러분의 나라에서 봄에는 어떤 과일 또는 어떤 음식을 많이 먹어요? 댓글로 남겨 주세요 :)", "english": "The fruit people eat a lot in spring is strawberries. So at cafes there are many strawberry-based things like strawberry lattes, strawberry smoothies, and strawberry tiramisu. In your country, what fruit or food do you eat a lot in spring? Please leave a comment :)"},
         {"korean": "봄 다음은 여름이에요. 한국의 여름은 정말 너무 더워요. 많이 덥지만 거의 모든 곳에 에어컨이 있어서 괜찮아요. 그리고 여름에 날씨가 좋을 때가 많지만 비가 올 때도 많아요. 비가 계속 오면 '장마'라고 해요. 장마 때 며칠 동안 계속 비가 와요. 여름에 학생들에게 여름 방학이 있고 회사원들은 휴가가 있어서 쉴 수 있어요. 많은 사람들이 바닷가에 가요. 기차, 차를 타고 바닷가에 가서 친구들하고 놀아요. 바닷가에서 수영을 할 수 있어요.", "english": "After spring comes summer. Summer in Korea is really, really hot. It is very hot, but almost everywhere has air conditioning, so it is okay. The weather is often nice in summer, but it also rains a lot. When it keeps raining we call it jangma (the rainy season). During jangma it rains continuously for several days. In summer students have summer vacation and office workers have holidays, so they can rest. Many people go to the beach. They take a train or car to the beach and have fun with friends. You can swim at the beach."},
         {"korean": "그리고 수영장도 가요. 한국에 큰 수영장이 있어요. 서울에서 멀지 않고 수영장에서 재미있게 놀 수 있어요. 저는 여름에 카페에 자주 가요. 카페에 에어컨이 있어서 시원한 커피하고 음료수를 마실 수 있어서 여름에 카페에 사람들이 많아요. 그리고 카페에서 시원한 빙수를 먹을 수 있어서 카페에 자주 가요. 요즘 많은 빙수가 있는데 저는 딸기 빙수하고 인절미 빙수를 제일 좋아해요. 여름에 자주 먹는 과일은 수박이에요. 그리고 삼계탕도 먹어요. 삼계탕은 닭 요리예요. 따뜻한 음식이지만 여름에 자주 먹어요.", "english": "People also go to swimming pools. There is a big water park in Korea. It is not far from Seoul and you can have a fun time there. I often go to cafes in summer. Cafes have air conditioning and you can drink cold coffee and other drinks, so cafes are crowded in summer. You can also eat cold bingsu (shaved ice) at cafes, so I go often. There are many kinds of bingsu these days, and I like strawberry bingsu and injeolmi bingsu the most. The fruit people eat a lot in summer is watermelon. People also eat samgyetang, which is a chicken dish. It is a warm food, but people eat it often in summer."},
         {"korean": "여름이 끝나고 가을이 와요. 가을에는 단풍이 들어서 단풍 구경을 자주 해요. 가을에 날씨가 시원하고 단풍이 예뻐서 가을에 등산을 많이 해요. 가을에는 날씨가 시원해서 한국 사람들이 예쁘고 멋있는 옷을 입어요. 왜냐하면 여름은 너무 덥고 겨울에는 너무 추워서 멋있고 예쁜 옷을 잘 못 입어요. 코트, 니트, 스웨터, 카디건하고 셔츠 등을 입을 수 있어요. 가을에는 봄하고 날씨가 비슷해요.", "english": "After summer ends, autumn comes. In autumn the leaves turn color, so people often go to see the foliage. The weather is cool and the autumn leaves are pretty, so people go hiking a lot in autumn. Because the weather is cool, Korean people wear pretty, stylish clothes. That is because summer is too hot and winter is too cold to wear nice, pretty clothes. You can wear coats, knits, sweaters, cardigans, shirts, and so on. Autumn weather is similar to spring."},
         {"korean": "아침에는 조금 춥고 오후에는 따뜻하지만 밤에 또 추워요. 그래서 옷을 여러 개 입어요. 가을에도 꽃이 펴요. 코스모스가 펴요. 코스모스가 정말 예뻐서 코스모스 축제도 있어요. 그래서 축제에 가서 사진도 찍고 친구들하고 놀아요.", "english": "In the morning it is a little cold, in the afternoon it is warm, but at night it gets cold again. So people wear several layers of clothes. Flowers bloom in autumn too. Cosmos flowers bloom. Cosmos are really pretty, so there are even cosmos festivals. So I go to the festivals, take photos, and hang out with friends."},
         {"korean": "가을이 끝날 때 정말 추워요. 이제 겨울이에요. 겨울에는 정말 춥고 눈이 와요. 눈이 많이 오면 눈사람을 만들 수 있고 스키장에 가서 스키하고 보드를 탈 수 있어요. 한국에서는 몇 년 전부터 눈오리 만드는 것이 유행이에요. 저도 지난 겨울에 눈오리를 많이 만들었어요. 친구하고 같이 눈사람하고 눈오리를 만들면 재미있어요. 그리고 겨울에 스키장에 가서 스키하고 보드를 탈 수 있어요.", "english": "When autumn ends it gets really cold. Now it is winter. In winter it is really cold and it snows. When it snows a lot you can build a snowman, and you can go to a ski resort to ski and snowboard. In Korea, making snow ducks (nun-ori) has been popular for a few years. I made a lot of snow ducks last winter too. It is fun to make snowmen and snow ducks together with friends. And in winter you can go to a ski resort to ski and snowboard."},
         {"korean": "여러분은 스키를 탈 수 있어요? 저는 중학생 때 한 번 탔는데 지금은 잘 못 타요. 그리고 스키장에 가면 재미있지만 너무 멀고 추워서 스키장에 가는 것을 안 좋아해요. 사실 저는 눈을 별로 안 좋아해요. 왜냐하면 눈이 오면 길이 너무 미끄럽고 차가 많이 막혀요. 하지만 눈이 올 때는 눈이 정말 예뻐요. 그래서 눈을 보는 것은 좋아해요.", "english": "Can you ski? I skied once in middle school, but now I am not very good. Going to a ski resort is fun, but it is too far and cold, so I do not like going. Honestly, I do not really like snow, because when it snows the roads get very slippery and there is a lot of traffic. But when it is snowing the snow is really pretty, so I do like looking at it."},
         {"korean": "오늘은 한국의 날씨와 계절, 그리고 그 계절에 무엇을 하고 무엇을 먹어요? 이야기를 했어요. 지금 여러분의 나라는 날씨가 어때요? 그리고 무슨 계절이에요? 무엇을 하고 있어요? 댓글로 써 주세요 :) 그럼 다음에 또 봐요!", "english": "Today I talked about Korea's weather and seasons, and what people do and eat in each season. How is the weather in your country now? And what season is it? What are you doing? Please write it in the comments :) See you again next time!"}
       ]$json$::jsonb,
       $json$[
         {"term": "계절", "meaning": "season", "example": "한국의 계절은 봄, 여름, 가을, 겨울이 있어요."},
         {"term": "날씨", "meaning": "weather", "example": "봄에는 낮에는 따뜻하지만 밤에는 추워요."},
         {"term": "꽃이 피다", "meaning": "(flowers) to bloom", "example": "4월에 꽃이 많이 피어요."},
         {"term": "꽃구경", "meaning": "flower viewing", "example": "사람들이 꽃구경을 하러 가요."},
         {"term": "장마", "meaning": "the rainy season (monsoon)", "example": "비가 계속 오면 '장마'라고 해요."},
         {"term": "단풍", "meaning": "autumn leaves / foliage", "example": "가을에는 단풍 구경을 자주 해요."},
         {"term": "시원하다", "meaning": "to be cool (weather)", "example": "가을에 날씨가 시원해요."},
         {"term": "축제", "meaning": "festival", "example": "봄에는 벚꽃 축제가 있어요."},
         {"term": "빙수", "meaning": "shaved-ice dessert", "example": "저는 딸기 빙수를 제일 좋아해요."},
         {"term": "스키장", "meaning": "ski resort", "example": "겨울에 스키장에 가서 스키를 타요."},
         {"term": "미끄럽다", "meaning": "to be slippery", "example": "눈이 오면 길이 너무 미끄러워요."},
         {"term": "차가 막히다", "meaning": "to be stuck in traffic", "example": "눈이 오면 차가 많이 막혀요."}
       ]$json$::jsonb,
       $json$[
         {"question": "한국에서 보통 몇 월부터 몇 월까지 봄이에요?", "options": ["3월부터 5월까지", "6월부터 8월까지", "9월부터 11월까지", "12월부터 2월까지"], "answerIndex": 0, "explanation": "한국은 보통 3월부터 5월까지 봄이에요."},
         {"question": "화자는 여름에 어떤 빙수를 제일 좋아해요?", "options": ["딸기 빙수하고 인절미 빙수", "수박 빙수", "커피 빙수", "초콜릿 빙수"], "answerIndex": 0, "explanation": "딸기 빙수하고 인절미 빙수를 제일 좋아해요."},
         {"question": "화자는 왜 눈을 별로 안 좋아해요?", "options": ["길이 미끄럽고 차가 많이 막혀서", "눈이 안 예뻐서", "눈사람을 싫어해서", "스키를 좋아해서"], "answerIndex": 0, "explanation": "눈이 오면 길이 미끄럽고 차가 막혀서 별로 안 좋아해요. 하지만 눈을 보는 것은 좋아해요."}
       ]$json$::jsonb
WHERE EXISTS (SELECT 1 FROM users WHERE id = 1);

INSERT INTO reading_units (user_id, episode, title, title_english, category, level, summary, source,
                           grammar_note, paragraphs, vocab, quiz)
SELECT 1, 'EP 03', '하루 일과', 'Daily Schedule', 'DAILY_LIFE', 'Beginner',
       'Choisusu walks through a full day in her life: a weekday split between her morning cafe job and afternoon/evening Korean lessons, what she does when the cafe is busy or quiet, her late-night wind-down, and a slower weekend with brunch and study.',
       'Choisusu Korean Podcast',
       $json${
         "pattern": "-부터 -까지 (from ~ to ~)",
         "explanation": "Use -부터 ... -까지 with times or places to say \"from ~ to ~\". Example: 아홉 시부터 열두 시까지 일해요 = I work from nine to twelve. The episode also teaches Noun도 = \"also / too\": 카페에서도 일해요 = I work at the cafe too."
       }$json$::jsonb,
       $json$[
         {"korean": "여러분 안녕하세요! 오늘은 하루 일과에 대해서 이야기할 거예요. 하루 일과는 보통 오전에 무엇을 해요? 그리고 오후에 무엇을 해요? 하루 동안 무엇을 해요? 이야기하는 거예요. 여러분은 평일에 보통 무엇을 해요?", "english": "Hello everyone! Today I am going to talk about my daily routine. A daily routine is talking about what you usually do in the morning, what you do in the afternoon, and what you do throughout the day. What do you usually do on weekdays?"},
         {"korean": "저는 평일에 일을 하는데 수요일에는 쉬어요. 그리고 보통 아침 아홉 시부터 열두 시까지 일하고 한 시부터 다섯 시, 그리고 저녁 여덟 시부터 열 시까지 일해요. 지금은 한국어를 가르치고 카페에서도 일하고 있어요. 아침에는 카페에서 일하고 오후하고 밤에는 한국어를 가르쳐요.", "english": "I work on weekdays, but I rest on Wednesdays. I usually work from nine to twelve in the morning, from one to five, and from eight to ten in the evening. Right now I teach Korean and also work at a cafe. In the morning I work at the cafe, and in the afternoon and at night I teach Korean."},
         {"korean": "수요일에는 아침부터 밤까지 카페에서 일해요. 또는 쉴 때도 있어요. 그리고 주말에는 토요일만 일하고 일요일은 쉬어요. 저는 평일에 보통 아침 8시에 일어나요. 일어난 후에 씻고 옷을 입고 일하러 갈 준비를 해요. 저는 아침잠이 많아서 아침에 일어나는 것이 힘들어요. 그래서 아침에 좋아하는 노래를 들으면서 준비를 해요.", "english": "On Wednesdays I work at the cafe from morning to night. Or sometimes I take the day off. On weekends I only work on Saturday and rest on Sunday. On weekdays I usually wake up at 8 a.m. After waking up I wash up, get dressed, and get ready to go to work. I love my morning sleep, so getting up in the morning is hard. That is why I get ready while listening to songs I like."},
         {"korean": "아침 9시에 카페가 시작해서 8시 50분까지 가서 준비해요. 카페에서 일하는 것은 재미있지만 조금 힘들고 피곤해요. 처음에는 커피 만드는 것이 어려웠지만 지금은 전보다 쉽고 빨리 만들 수 있어요. 여러분은 커피를 좋아해요? 저는 커피를 좋아해서 일할 때 커피를 많이 마셔요.", "english": "The cafe opens at 9 a.m., so I get there by 8:50 to prepare. Working at the cafe is fun, but a little hard and tiring. At first making coffee was difficult, but now it is easier than before and I can make it quickly. Do you like coffee? I like coffee, so I drink a lot of it while working."},
         {"korean": "그리고 에이드를 좋아해서 자몽 에이드하고 청포도 에이드도 자주 마셔요. 커피를 너무 많이 마셔서 몸이 안 좋아지는 것 같아서 요즘 커피를 자주 안 먹고 있어요. 그리고 요거트 스무디나 다른 음료는 설탕이 많아서 많이 마시면 살이 쪄요. 그래서 요즘은 물을 많이 마시고 있어요.", "english": "I also like ade drinks, so I often have grapefruit ade and green grape ade too. I think drinking too much coffee is making me feel unwell, so these days I am not drinking it as often. Also, yogurt smoothies and other drinks have a lot of sugar, so if you drink a lot you gain weight. So these days I am drinking a lot of water."},
         {"korean": "보통 아침 9시부터 12시까지 카페에서 일하는데 사람이 많을 때도 있고 사람이 별로 없을 때도 있어요. 9시부터 10시 또는 11시까지 쿠키하고 빵을 구워요. 그리고 11시부터 1시까지는 조금 바빠요. 아마 사람들이 점심을 먹어서 커피를 마시고 싶은 것 같아요. 날씨가 추웠을 때는 따뜻한 커피를 많이 만들었는데 요즘 날씨가 더워요.", "english": "I usually work at the cafe from 9 a.m. to 12, and sometimes there are many customers and sometimes hardly any. From 9 to 10 or 11 I bake cookies and bread. From 11 to 1 it gets a bit busy. I guess people want coffee after eating lunch. When the weather was cold I made a lot of hot coffee, but these days the weather is hot."},
         {"korean": "그래서 많은 사람들이 아이스 아메리카노하고 아이스 라테를 마셔요. 최근에는 아이스 아메리카노를 정말 많이 시키셔서 아이스 아메리카노만 한 번에 10잔을 만들었어요. 손님이 많아서 바쁘지만 커피 만드는 것이 재미있어서 손님이 없는 것보다 많은 것이 더 좋아요. 손님이 없을 때는 쉴 수 있지만 너무 심심해요. 손님이 없을 때 보통 유튜브를 보거나 일을 해요. 그리고 핸드폰으로 게임도 해요. 청소도 해요. 일본어하고 프랑스어를 공부할 때도 있어요.", "english": "So many people drink iced americanos and iced lattes. Recently people ordered so many iced americanos that I made ten iced americanos at once. It is busy when there are many customers, but making coffee is fun, so having many is better than having none. When there are no customers I can rest, but it is too boring. When it is empty I usually watch YouTube or do other work. I also play games on my phone, clean, and sometimes study Japanese and French."},
         {"korean": "열두 시에는 카페에서 퇴근해서 집에 가요. 가서 점심을 먹고 한국어 수업을 준비해요. 보통 한 시 반부터 한국어 수업이 있어요. 한국어 수업을 할 때는 조금 긴장되지만 재미있어요. 오후에는 보통 수업이 두 개가 있어요. 많으면 세 개도 있어요. 수업이 없으면 낮잠을 잘 수도 있어요. 보통 다섯 시 반에 수업이 끝나요.", "english": "At twelve I clock out of the cafe and go home. I go home, eat lunch, and prepare for my Korean lessons. I usually have Korean lessons starting at 1:30. When I teach Korean I get a little nervous, but it is fun. In the afternoon I usually have two classes; when there are many, three. If I have no class I can take a nap. My classes usually end at 5:30."},
         {"korean": "그러면 좀 쉬고 저녁을 만들어서 먹어요. 저녁을 먹고 저녁 수업을 준비해요. 또는 카페에 가서 일할 때도 있어요. 집에서 카페까지 20분 정도 걸려서 자전거를 타고 가요. 보통 저녁 수업은 여덟 시에 시작해요. 전에는 밤 11시 30분까지 일했었는데 너무 힘들어서 요즘은 밤 10시까지만 일해요. 수업 전에 학생들의 숙제를 확인하고 수업을 하고 끝난 후에 문법하고 단어를 보내요. 그리고 다른 학생들의 질문에 답장을 보내요. 그래서 수업이 끝나고 30분 후에 모든 일이 끝나요.", "english": "Then I rest a bit and cook dinner. After dinner I prepare for the evening class. Or sometimes I go work at the cafe. It takes about 20 minutes from home to the cafe, so I ride my bike. Evening classes usually start at eight. I used to work until 11:30 p.m., but it was too hard, so these days I only work until 10 p.m. Before class I check the students' homework, teach, and after it ends I send grammar and vocabulary. I also reply to other students' questions. So all my work finishes 30 minutes after class ends."},
         {"korean": "일이 다 끝나면 책상하고 방을 정리하고 잠시 쉬어요. 이때 텔레비전을 보거나 핸드폰을 해요. 모든 일이 끝나면 보통 10시 반이나 11시예요. 좀 쉬고 샤워를 하고 잘 준비를 해요. 자기 전에 친구들하고 이야기도 하고 재미있는 영상하고 드라마를 봐요. 그러면 보통 새벽 한 시에 자요.", "english": "When all my work is done, I tidy my desk and room and rest for a while. At this time I watch TV or use my phone. When everything is finished it is usually 10:30 or 11. I rest a bit, take a shower, and get ready for bed. Before sleeping I chat with friends and watch fun videos and dramas. Then I usually go to sleep around 1 a.m."},
         {"korean": "주말에는 토요일에는 일하고 일요일에는 쉬어요. 저는 보통 수요일하고 일요일에 쉬어서 친구들을 수요일 또는 일요일에 만나요. 쉬는 날에는 늦게 일어나요. 보통 열 시나 열한 시에 일어나요. 그리고 집에서 늦게 아침을 먹어요. 아침을 늦게 먹어서 점심시간이랑 비슷해요.", "english": "On weekends I work on Saturday and rest on Sunday. I usually rest on Wednesday and Sunday, so I meet my friends on Wednesday or Sunday. On my days off I wake up late, usually at ten or eleven. Then I eat a late breakfast at home. Because I eat breakfast late, it is around lunchtime."},
         {"korean": "이것을 한국어로 '아점(아침&점심)'이라고 해요. 쉬는 날에는 아점을 먹어요. 그리고 쉬는 날에 영어, 일본어나 프랑스어 수업을 들어요. 그리고 공부를 하고 수업 준비를 할 때도 있어요. 그리고 팟캐스트 준비를 해요.", "english": "In Korean we call this ajeom (a blend of achim 'breakfast' and jeomsim 'lunch'). On my days off I eat brunch. On those days I also take English, Japanese, or French lessons. Sometimes I study and prepare my own lessons. And I prepare the podcast."},
         {"korean": "오늘은 이렇게 제 하루 일과에 대해서 이야기했어요. 여러분은 평일하고 주말에 무엇을 해요? 언제 일어나고 언제 출근해요? 그리고 주말에는 무엇을 해요? 여러분의 하루 일과를 댓글로 써 주세요! :) 그럼 다음에 또 봐요!", "english": "Today I talked about my daily routine like this. What do you do on weekdays and weekends? When do you wake up and when do you go to work? And what do you do on weekends? Please write your daily routine in the comments! :) See you again next time!"}
       ]$json$::jsonb,
       $json$[
         {"term": "하루 일과", "meaning": "daily routine / schedule", "example": "오늘은 하루 일과에 대해서 이야기할 거예요."},
         {"term": "평일", "meaning": "weekday", "example": "저는 평일에 일을 해요."},
         {"term": "주말", "meaning": "weekend", "example": "주말에는 토요일만 일해요."},
         {"term": "출근하다", "meaning": "to go to work / commute", "example": "여러분은 언제 출근해요?"},
         {"term": "일어나다", "meaning": "to wake up / get up", "example": "평일에 보통 아침 8시에 일어나요."},
         {"term": "가르치다", "meaning": "to teach", "example": "오후하고 밤에는 한국어를 가르쳐요."},
         {"term": "피곤하다", "meaning": "to be tired", "example": "카페 일은 조금 힘들고 피곤해요."},
         {"term": "낮잠", "meaning": "nap", "example": "수업이 없으면 낮잠을 잘 수도 있어요."},
         {"term": "자전거", "meaning": "bicycle", "example": "자전거를 타고 카페에 가요."},
         {"term": "살이 찌다", "meaning": "to gain weight", "example": "설탕이 많아서 많이 마시면 살이 쪄요."},
         {"term": "아점", "meaning": "brunch (breakfast + lunch)", "example": "쉬는 날에는 아점을 먹어요."}
       ]$json$::jsonb,
       $json$[
         {"question": "화자는 보통 무슨 요일에 쉬어요?", "options": ["수요일하고 일요일", "월요일하고 화요일", "토요일하고 일요일", "매일 쉬어요"], "answerIndex": 0, "explanation": "보통 수요일하고 일요일에 쉬어요."},
         {"question": "화자는 카페에서 무슨 일을 해요?", "options": ["커피를 만들고 쿠키와 빵을 구워요", "청소만 해요", "요리사로 일해요", "계산만 해요"], "answerIndex": 0, "explanation": "카페에서 커피를 만들고, 9시부터 쿠키하고 빵을 구워요."},
         {"question": "'아점'은 무슨 뜻이에요?", "options": ["아침과 점심을 합친 늦은 식사", "저녁 식사", "아침 운동", "점심에 듣는 수업"], "answerIndex": 0, "explanation": "아침을 늦게 먹어서 점심시간과 비슷한 식사를 '아점(아침&점심)'이라고 해요."}
       ]$json$::jsonb
WHERE EXISTS (SELECT 1 FROM users WHERE id = 1);
