-- Refresh tokens for "log in once, stay logged in" sessions.
--
-- The access token (JWT) stays short-lived; when it expires the client posts its
-- refresh token to /api/auth/refresh to get a new access token without re-login.
--
-- Security notes:
--  * We store only a SHA-256 HASH of the refresh token, never the raw value, so a
--    DB leak does not hand out usable tokens.
--  * Rotation: each refresh revokes the presented token (sets revoked_at) and
--    issues a new one. Logout revokes the token too.
--  * ON DELETE CASCADE removes a user's tokens when the user is deleted.

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,   -- SHA-256 hex digest of the raw token
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Fast lookup of a user's active tokens (e.g. logout-all).
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON refresh_tokens (user_id);
