CREATE TABLE IF NOT EXISTS vocab_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category VARCHAR(100) NOT NULL,
    term VARCHAR(200) NOT NULL,
    meaning TEXT NOT NULL,
    example TEXT,
    mastery INTEGER NOT NULL DEFAULT 0,
    next_review_date DATE NOT NULL DEFAULT CURRENT_DATE,
    tags JSONB NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_vocab_cards_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_vocab_cards_user_id ON vocab_cards (user_id);
CREATE INDEX IF NOT EXISTS idx_vocab_cards_next_review ON vocab_cards (user_id, next_review_date);
CREATE INDEX IF NOT EXISTS idx_vocab_cards_category ON vocab_cards (user_id, category);