-- Per-user progress for the Foundations / Learn module. Lesson CONTENT lives in
-- the frontend seed (lib/foundations-data.ts); only the user's completion state
-- is server-backed here so it syncs across devices.
CREATE TABLE IF NOT EXISTS foundation_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    lesson_id VARCHAR(60) NOT NULL,
    track VARCHAR(20) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT false,
    accuracy INT NOT NULL DEFAULT 0,
    attempts INT NOT NULL DEFAULT 0,
    last_attempt_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_foundation_progress_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_foundation_progress_user_lesson UNIQUE (user_id, lesson_id)
);

CREATE INDEX IF NOT EXISTS idx_foundation_progress_user ON foundation_progress (user_id);
