ALTER TABLE sentence_corrections
    ADD COLUMN IF NOT EXISTS mastery INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS next_review_date DATE NOT NULL DEFAULT CURRENT_DATE,
    ADD COLUMN IF NOT EXISTS ease_factor NUMERIC(4, 2) NOT NULL DEFAULT 2.50,
    ADD COLUMN IF NOT EXISTS interval_days INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS repetitions INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS lapses INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_reviewed_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_sentence_corrections_due
    ON sentence_corrections (user_id, next_review_date);
