-- Per-user progress (start/complete/quiz result) for reading units, so a
-- unit's read/quiz state syncs across devices instead of living only in the
-- browser's localStorage (lib/reading.ts on the frontend).
CREATE TABLE IF NOT EXISTS reading_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    unit_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'not_started',
    quiz_score INT,
    quiz_total INT,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_reading_progress_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_reading_progress_unit FOREIGN KEY (unit_id) REFERENCES reading_units (id) ON DELETE CASCADE,
    CONSTRAINT uq_reading_progress_user_unit UNIQUE (user_id, unit_id)
);

CREATE INDEX IF NOT EXISTS idx_reading_progress_user ON reading_progress (user_id);
