CREATE TABLE IF NOT EXISTS daily_phrases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    phrase_date DATE NOT NULL DEFAULT CURRENT_DATE,
    phrase_kr VARCHAR(300) NOT NULL,
    meaning_en TEXT NOT NULL,
    romanization VARCHAR(300),
    when_to_use TEXT,
    formality_level VARCHAR(80),
    similar_expressions JSONB NOT NULL DEFAULT '[]',
    learned BOOLEAN NOT NULL DEFAULT FALSE,
    model_used VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_daily_phrases_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_daily_phrases_user_date UNIQUE (user_id, phrase_date)
);

CREATE INDEX IF NOT EXISTS idx_daily_phrases_user_id ON daily_phrases (user_id);
CREATE INDEX IF NOT EXISTS idx_daily_phrases_user_date ON daily_phrases (user_id, phrase_date DESC);
